server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/labinas/atmlocator-config-server.git
          clone-on-start: true